### ISSUE TITLE
Setup & maintain a shared Arktos cluster for multi-tenancy teams

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#109]
**What would you like to be added**:
Setup & maintain a cluster for multi-tenancy testing, and issue certs for tenants.

**Why is this needed**:
To verify our work and find other potential problems.

**Comment by pdgetrf** [comment]
server: 
```bash
ssh root@ec2-54-185-239-246.us-west-2.compute.amazonaws.com
```
password sent in separate email.

**Comment by pdgetrf** [comment]
running arktos master branch

![image](https://user-images.githubusercontent.com/252020/76361039-64fec700-62db-11ea-84b0-83c5eb53cf2a.png)

**Comment by pdgetrf** [comment]
credential (user, cert and context) can be created with the following script:
```bash
root@ip-172-31-22-153:~/sandbox# ./create_cred.sh
Usage: create_cred.sh [user]
```

role and role binding can be created using
```bash
root@ip-172-31-22-153:~/sandbox# ./create_role.sh
Usage: create_cred.sh [user]
```

For testing, created tenant can be seen from rbac log after using:
```bash
kubectl --context=pengdu-context get pods
```
![image](https://user-images.githubusercontent.com/252020/76361262-dcccf180-62db-11ea-8eeb-e9146a666b20.png)

Also we can see this user cannot access other namespace:
```bash
root@ip-172-31-22-153:~/sandbox# kubectl --context=pengdu-context get pods
No resources found.
root@ip-172-31-22-153:~/sandbox# kubectl --context=pengdu-context get pods -n kube-system
Error from server (Forbidden): pods is forbidden: User "pengdu" cannot list resource "pods" in API group "" in the namespace "kube-system"
```
