### ISSUE TITLE
Decide the right API group and version for network objects

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#111]
**What would you like to be added**:
Decide the right API group and version for the newly proposed network object. Or define it as CRDs for easier adopted by other projects.

**Why is this needed**:

**Comment by h-w-chen** [comment]
as #247 is coded, 'arktos.futurewei.com/v1' is the GV for this network CR.

**Comment by h-w-chen** [comment]
network is defined as CRD, in arktos.futureeoi.com/v1
