### ISSUE TITLE
AWS: Add workload-controller-manager to aws-kube-up and start-kubemark

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#168]
**What happened**:
kube-up and start-kubemark on AWS missing workload-controller-manger
**What you expected to happen**:
workload-controller-manger included
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
https://github.com/futurewei-cloud/arktos/pull/127
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by vinaykul** [comment]
Fixed in above commit.
