### ISSUE TITLE
AWS: Register kubemark master as a node

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#171]
**What happened**:
kubectl get node cannot display master node after start-kubemark, only hollow-node displayed.
**What you expected to happen**:
Register kubemark master as a node
**How to reproduce it (as minimally and precisely as possible)**:
run perf-tests after start kube-mark, and found error:
```
E0401 00:10:11.112849   21622 clusterloader.go:198] Test Finished
E0401 00:10:11.112853   21622 clusterloader.go:199]   Test: testing/density/config.yaml
E0401 00:10:11.112858   21622 clusterloader.go:200]   Status: Fail
E0401 00:10:11.112863   21622 clusterloader.go:202]   Errors: [config reading error: replacing placeholders error: template: :30:22: executing "" at <DivideInt (MaxInt $MIN_LATENCY_PODS .Nodes) $namespaces>: error calling DivideInt: division by zero]
```
this caused by kubemark cluster cannot get master information correctly because kubemark master didn't registered as node.
```
I0401 00:10:10.954216   21622 clusterloader.go:226] Using config: {ClusterConfig:{KubeConfigPath:[PWD]/arktos/test/kubemark/resources/kubeconfig.kubemark Nodes:2 Provider:kubemark EtcdCertificatePath:/etc/srv/kubernetes/pki/etcd-apiserver-server.crt EtcdKeyPath:/etc/srv/kubernetes/pki/etcd-apiserver-server.key EtcdInsecurePort:2382 MasterIPs:[] MasterInternalIPs:[] MasterName: KubemarkRootKubeConfigPath:[PWD]/.kube/config DeleteStaleNamespaces:false IsSSHToMasterSupported:true IsAPIServerPprofEnabled:true} ReportDir:[PWD]/logs/perf-test/aws-100/0331 EnableExecService:false TestScenario:{Identifier: ConfigPath: OverridePaths:[]} PrometheusConfig:{EnableServer:false TearDownServer:true ScrapeEtcd:false ScrapeNodeExporter:false ScrapeKubelets:false ScrapeKubeProxy:true}}
```
**Anything else we need to know?**:
https://github.com/futurewei-cloud/arktos/pull/127
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by vinaykul** [comment]
Fixed in above commit.
