### ISSUE TITLE
Revert changes in ObjectKey() and Add a new method ObjectKeyWithTenancy()

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#182]
(To add more details)

**Comment by chenqianfzh** [comment]
We cannot have two different obj key generation functions. The object caches needs one general key generation function for all the objects of all resource type. See code in "/staging/src/k8s.io/client-go/tools/cache/reflector.go" and "staging/src/k8s.io/client-go/tools/cache/shared_informer.go", and search for "MetaNamespaceKeyFunc" for more details.

However, the keys generated can still work in a backward-compatible manner. Three different funcs to split the key into tenant/namespace/ObjectNames are created (in staging/src/k8s.io/client-go/tools/cache/store.go) to cope with it:
1. SplitMetaNamespaceKey. This is func exists the multi-tenancy change. Now its interface is exactly same as before. It returns the namespace/objectName (no tenant) based on the input.  As a result, the components which have not gone through multi-tenancy change should use it.
2. SplitMetaTenantNamespaceKey. It returns the tenant/namespace/ObjectName based on the input key. The component working on namespace-scoped objects should use this func in multi-tenancy change.
2. SplitMetaTenantKey. It returns the tenant/ObjectName based on the input key. The component working on tenant-scoped objects should use this func in multi-tenancy change.

**Comment by chenqianfzh** [comment]
cleared in offline discussion
