### ISSUE TITLE
Make "tenant.ALL" working

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#184]

**Comment by chenqianfzh** [comment]
1. TenantAll is defined as follows in staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go:
   TenantAll string = ""

2. The List() func for each listers in client-go is implemented to run across all the tenants. Each list() func calls ListAll() in staging/src/k8s.io/client-go/tools/cache/listers.go, which has been updated to list objects across all the tenants. 

3.Informers are updated to watch across all tenants. See staging/src/k8s.io/apiextensions-apiserver/pkg/client/informers/externalversions/factory.go.

**Comment by chenqianfzh** [comment]
Tenant.All for System tenant after short-path is in.

**Comment by chenqianfzh** [comment]
How to list objects of a given namespace across all tenants? The current URL scheme does not support it.

**Comment by h-w-chen** [comment]
One scenario we need to support is for (shared) controllers (e.g. tenant controller) to lw the Network CRD of __all tenant__.  on CLI, $ kubectl --all-tenants get Network should return all network CRs across all tenants.

**Comment by XiaoningDing** [comment]
The initial decision is to use a reserved tenant name "all" for tenant.ALL.  Changes are required in clientGo and in endpoint resolution. The approach needs to be verified.

**Comment by chenqianfzh** [comment]
https://github.com/futurewei-cloud/arktos/pull/311
