### ISSUE TITLE
Unable to write event: 'can't create an event with tenant 'zz' in tenant 'default''

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#212]
E0420 21:19:22.768741   11543 event.go:250] Unable to write event: 'can't create an event with tenant 'zz' in tenant 'default'' (may retry after sleeping)

E0420 21:19:22.768777   11543 event.go:195] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"nginx-deployment-56644bf55b-ggr8f.1607a3aec6bff540", GenerateName:"", Tenant:"zz", Namespace:"namespace-a", SelfLink:"", UID:"", HashKey:0, ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"namespace-a", Name:"nginx-deployment-56644bf55b-ggr8f", UID:"335b2a11-77d2-4215-acde-58fc9b75cf8e", APIVersion:"v1", ResourceVersion:"592", FieldPath:"", Tenant:"zz"}, Reason:"Scheduled", Message:"Successfully assigned zz/namespace-a/nginx-deployment-56644bf55b-ggr8f to ip-172-30-0-148", Source:v1.EventSource{Component:"default-scheduler", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf9fa2252b3e2d40, ext:261196163751, loc:(*time.Location)(0xc5e45a0)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf9fa2252b3e2d40, ext:261196163751, loc:(*time.Location)(0xc5e45a0)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}' (retry limit exceeded!)

Repo steps:
1. Master branch
2. Steps to repo:
   i. $./hack/arktos-up.sh
   ii. Create tenant a
   iii. Create namespace an in tenant a
   iv. Create deployment ad in tenant/namespace: a/an
3. Check /tmp/kubelet.log
Every 10 seconds, got log

Unable to write event: 'can't create an event with tenant 'a' in tenant 'default'' (may retry after sleeping)

**Comment by chenqianfzh** [comment]
Please give the following details:
1. which branch?
2. steps to repro?
3. Which component? which log file?

**Comment by Sindica** [comment]
> Please give the following details:
> 
> 1. which branch?
> 2. steps to repro?
> 3. Which component? which log file?

Updated in issue description

**Comment by Sindica** [comment]
I don't see the event anymore. Mark this issue as resolved
