### ISSUE TITLE
endpoint resource should support tenant 

### ISSUE THREAD

**Issue by h-w-chen** [futurewei-cloud/arktos#23]
**What happened**:
getting endpoint resource gets no tenant information 

**What you expected to happen**:
endpoint resource should have tenant in its metadata

**How to reproduce it (as minimally and precisely as possible)**:
kubectl get endpoint --all-namespaces

**Anything else we need to know?**:
this lack of multi-tenancy support of endpoint type seems lead to api server perf degradation observed by kubemark perf test (5000 node, ~20K pods).

**Comment by chenqianfzh** [comment]
Code change is done in https://github.com/futurewei-cloud/arktos/commit/d44f63e5d9973b7518eb6f54d950c6667fe47e65

BTW, to see the endpoints in the system
kubectl get endpoint --all-namespaces --all-tenants
