### ISSUE TITLE
copyright are wrongly updated when doing 'make update'

### ISSUE THREAD

**Issue by dingyin** [futurewei-cloud/arktos#3]
**What happened**:
After running 'make update', a lot of unchanged files are updated with new copyright.

**What you expected to happen**:
No change for unchanged files.

**How to reproduce it (as minimally and precisely as possible)**:
Clean clone Arktos repo, then run 'make update'.

**Anything else we need to know?**:
- Seen these error messages on screen:
Inspecting copyright files, writing logs to _output/ArktosCopyrightTool.log
sed: 1: "/Users/yinding/workspac ...": transform strings are not the same length

- In log file, sample error messages are:
Copied file /Users/yinding/workspace/src/k8s.io/kubernetes/pkg/cloudfabric-controller/replicaset/doc.go has K8s copyright but not Arktos copyright. Skipping.
Copied file /Users/yinding/workspace/src/k8s.io/kubernetes/pkg/cloudfabric-controller/replicaset/replica_set_utils.go has K8s copyright but not Arktos copyright. Skipping.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
I did not make any changes. Running ./hack/arktos-up.sh on master, got the following files modified:

	modified:   cmd/kubeadm/app/apis/kubeadm/v1beta1/zz_generated.conversion.go
	modified:   pkg/apis/apps/v1/zz_generated.defaults.go
	modified:   pkg/apis/apps/v1beta1/zz_generated.defaults.go
	modified:   pkg/apis/apps/v1beta2/zz_generated.defaults.go
	modified:   pkg/apis/batch/v1/zz_generated.defaults.go
	modified:   pkg/apis/core/v1/zz_generated.defaults.go
	modified:   pkg/apis/extensions/v1beta1/zz_generated.defaults.go

Changes:
-Copyright 2020 Authors of Arktos - file modified.

**Comment by vinaykul** [comment]
Closing this issue - this was not a copyright tool problem. It was triggered due to a missed custom_metric generated file checkin between Jan 24 and Feb 18.

Generated file changes and gofmt changes seem to be often missed in PRs due to missed make update before sending PRs. One possible way to prevent this is to reject PRs if make update, make all , make quick-release steps leave any checked-out files.
