### ISSUE TITLE
Use Customized ETCD 3.4.4 in Arktos up/e2e test/performance test

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#315]
**What would you like to be added**:
Build and import the following ETCD/etcdctl tool into arktos.
https://github.com/futurewei-cloud/etcd/tree/release-3.4-ETCDPartition-RevGeneration

Test in the following scenarios and make necessary changes:
. arktos-up
. make update.
. make test
. integration test
. e2e test
. performance test

**Why is this needed**:
To make sure the new ETCD binary works in arktos up and other daily tests.

**Comment by Sindica** [comment]
I don't think current CI uses ETCD arktos 3.4.4.
The following commit updated resource version from float64 to uint64
https://github.com/futurewei-cloud/arktos/commit/3f91cac7dcbaed9b5cb1981de329dc61e93c7376

Current related ETCD update merged at 6.22 & 6.24. CI still succeed w/o the above changes means we are not using ETCD arktos version.

**Comment by jshaofuturewei** [comment]
From the CI log it finds the customized etcd but not sure if the system start etcd from the customerized version. Might need look into jelkins and find out.

**Comment by Sindica** [comment]
There is a fix for make update: https://github.com/futurewei-cloud/arktos/pull/506

**Comment by Sindica** [comment]
ETCD 3.4.4.arktos-1 is used in above mentioned area.

**Comment by Sindica** [comment]
This PR https://github.com/futurewei-cloud/arktos/pull/475 enabled ETCD 3.4.4.arktos-1 in perf test.
