### ISSUE TITLE
Benchmark test for ETCD 3.4.4

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#318]
**What would you like to be added**:
Using the ETCD benchmark tools to check ETCD 3.4.4 performance for community version & customized version.

. Community version:
https://github.com/etcd-io/etcd branch release 3.4
Commit 0b9cfa86772fa1ca9f4fc0a402ac6c73ffb599a0 (Seems like the latest change for 3.4.4) - please verify with Joe

. Customized version:
https://github.com/futurewei-cloud/etcd/tree/release-3.4-ETCDPartition-RevGeneration

. Golang version 1.12.9 or 1.12.12 (Please verify with Joe)
. Related docs and tools:
- https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/performance.md
- https://github.com/etcd-io/etcd/tree/master/tools/benchmark (Need to build on release 3.4 branch due to golang version upgrade)
- https://etcd.io/docs/v3.4.0/demo/

**Why is this needed**:
Due to customized ETCD revision #, we need to know current upper limit of ETCD write per second. Other performance data are bonus.

**Comment by sonyafenge** [comment]
ETCD build: release: 3.4.4.   https://github.com/etcd-io/etcd/releases/tag/v3.4.4
--
ETCD Cluster: 3 members. AWS-t2.2xlarge
ETCD Client: 1  AWS-m5ad.4xlarge
ETCD Client GOLANG:12.9
  |   |   |   |   |   |   |   |  
Write:
benchmark --endpoints=${HOST_1}:2379 --target-leader --conns=1   --clients=1     put --key-size=8 --sequential-keys --total=10000   --val-size=256
benchmark --endpoints=${HOST_1}:2379 --target-leader  --conns=100   --clients=1000     put --key-size=8 --sequential-keys   --total=100000 --val-size=256
benchmark   --endpoints=${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379 --conns=100   --clients=1000     put --key-size=8 --sequential-keys   --total=100000 --val-size=256
  |   |   |   |   |   |   |   |  
Number of keys | Key size in bytes | Value size in   bytes | Number of   connections | Number of clients | Target etcd   server | Average read QPS   (Request/sec) | Average latency   per request | Average server   RSS (Mem Usage: top)
10,000 | 8 | 256 | 1 | 1 | leader only | 622 | 1.2ms | 64 MB
100,000 | 8 | 256 | 100 | 1000 | leader only | 41,758 | 23.7ms | 192MB
100,000 | 8 | 256 | 100 | 1000 | all members | 47,982 | 20.5ms | 192MB
  |   |   |   |   |   |   |   |  
  |   |   |   |   |   |   |   |  
Read:
benchmark   --endpoints=${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379 --conns=1   --clients=1 range YOUR_KEY --consistency=l --total=10000
benchmark   --endpoints=${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379 --conns=1   --clients=1 range YOUR_KEY --consistency=s --total=10000
benchmark   --endpoints=${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379 --conns=100   --clients=1000 range YOUR_KEY --consistency=l --total=100000
benchmark   --endpoints=${HOST_1}:2379,${HOST_2}:2379,${HOST_3}:2379 --conns=100   --clients=1000 range YOUR_KEY --consistency=s --total=100000
  |   |   |   |   |   |   |   |  
Number of   requests | Key size in bytes | Value size in   bytes | Number of   connections | Number of clients | Consistency | Average read QPS   (Request/sec) | Average latency   per request |  
10,000 | 8 | 256 | 1 | 1 | Linearizable | 1,137 | 0.9ms |  
10,000 | 8 | 256 | 1 | 1 | Serializable | 2,072 | 0.4ms |  
100,000 | 8 | 256 | 100 | 1000 | Linearizable | 21,083 | 4.7ms |  
100,000 | 8 | 256 | 100 | 1000 | Serializable | 39,081 | 2.5ms |
