### ISSUE TITLE
Maybe the user context should be set up automatically after creating a tenant

### ISSUE THREAD

**Issue by ZongbaoLiu** [futurewei-cloud/arktos#362]
I have read the document about Multi-Tenancy Setup Guide(https://github.com/futurewei-cloud/arktos/blob/master/docs/setup-guide/multi-tenancy-setup.md).
In this document, after creating a tenant, I need to manually set up the user context every time. 
If it is the following, is it more reasonable？
**When a new tenant is created, the user context is automatically setup for this tenant and its user "admin".**

**Comment by pdgetrf** [comment]
depending on what you mean by "automatically". 

the user context is usually on the tenant owner's machine, which is very likely not the same as the cluster. when a new tenant is created, the tenant creator will be given certs which he could use to set up the context on his own machine.

**Comment by ZongbaoLiu** [comment]
@pdgetrf  OK, I understand what you said, thanks.
