### ISSUE TITLE
Arktos-up encountered "unexpected invalid memory address or nil pointer dereference" in Kubelet 

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#373]
**What happened**:
Run arktos-up.sh, master start up. Without doing anything for a few minutes, got "W0615 17:31:10]: kubelet terminated unexpectedly, see /tmp/kubelet.log"

Kubelet.log has the following panic:

1134 W0615 17:30:24.436141   20555 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/run/virtlet.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /run/virtlet.sock: connect: co     nnection refused". Reconnecting...
1135 I0615 17:30:24.436175   20555 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00038a4e0, CONNECTING
1136 I0615 17:30:24.436186   20555 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00038a4e0, TRANSIENT_FAILURE
1137 E0615 17:30:24.439838   20555 remote_runtime.go:184] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: des     c = "transport: Error while dialing dial unix /run/virtlet.sock: connect: connection refused"
1138 E0615 17:30:24.439861   20555 kuberuntime_sandbox.go:278] ListPodSandbox failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dial     ing dial unix /run/virtlet.sock: connect: connection refused"
1139 E0615 17:30:24.439870   20555 kuberuntime_sandbox.go:250] getKubeletSandboxesByRuntime failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Er     ror while dialing dial unix /run/virtlet.sock: connect: connection refused"
1140 E0615 17:30:24.440304   20555 remote_runtime.go:288] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = Unavailable desc = all Sub     Conns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /run/virtlet.sock: connect: connection refused"
1141 E0615 17:30:24.440327   20555 kuberuntime_container.go:372] getKubeletContainers failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error wh     ile dialing dial unix /run/virtlet.sock: connect: connection refused"
1142 E0615 17:30:24.443970   20555 remote_runtime.go:184] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: des     c = "transport: Error while dialing dial unix /run/virtlet.sock: connect: connection refused"
1143 E0615 17:30:24.443991   20555 helpers.go:326] ListPodSandbox failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial uni     x /run/virtlet.sock: connect: connection refused"
1144 E0615 17:30:24.450208   20555 remote_runtime.go:288] ListContainers with filter nil from runtime service failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: des     c = "transport: Error while dialing dial unix /run/virtlet.sock: connect: connection refused"
1145 E0615 17:30:24.450244   20555 helpers.go:393] ListPodSandbox failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial uni     x /run/virtlet.sock: connect: connection refused"
1146 E0615 17:30:24.450345   20555 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
1147 goroutine 610 [running]:
1148 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x4a84260, 0xc5e0af0)
1149         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
1150 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
1151         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
1152 panic(0x4a84260, 0xc5e0af0)
1153         /usr/local/go/src/runtime/panic.go:522 +0x1b5
1154 k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).removeContainer(0xc00024db80, 0xc00160e4c0, 0x40, 0xc000a3d580, 0x42fbbf)
1155         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:915 +0x134
1156 k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).DeleteContainer(0xc00024db80, 0x53ce423, 0x7, 0xc00160e4c0, 0x40, 0x1, 0x1)
1157         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kuberuntime/kuberuntime_container.go:949 +0x3f
1158 k8s.io/kubernetes/pkg/kubelet.(*podContainerDeletor).deleteContainersInPod(0xc0010ec120, 0xc0003f4500, 0x40, 0xc000992080, 0x0)
1159         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/pod_container_deletor.go:98 +0xcc
1160 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).cleanUpContainersInPod(0xc001136000, 0xc001372d50, 0x24, 0xc0003f4500, 0x40)
1161         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2422 +0x11c
1162 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc001136000, 0xc000e49c20, 0x8c68520, 0xc001136000, 0xc0013938c0, 0xc001393920, 0xc0010f1080, 0x45d801)
1163         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:2022 +0xf76
1164 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc001136000, 0xc000e49c20, 0x8c68520, 0xc001136000)
1165         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1912 +0x307
1166 k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc001136000, 0xc000e49c20)
1167         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/kubelet.go:1442 +0x27c
1168 k8s.io/kubernetes/cmd/kubelet/app.startKubelet.func1()
1169         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1116 +0x3d
1170 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc001344660)
1171         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
1172 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001344660, 0x0, 0x0, 0x1, 0xc0000d60c0)
1173         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
1174 k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001344660, 0x0, 0xc0000d60c0)
1175         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
1176 created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
1177         /home/ubuntu/go/src/arktos/_output/local/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:1115 +0x9a
1178 E0615 17:30:24.450896   20555 kuberuntime_image.go:106] Pod is not set in imageSpec: {k8s.gcr.io/pause:3.1 nil}
1179 I0615 17:30:24.450913   20555 status_manager.go:154] Starting to sync pod status with apiserver
1180 I0615 17:30:24.450997   20555 kubelet.go:1885] Starting kubelet main sync loop.
1181 I0615 17:30:24.451079   20555 volume_manager.go:241] The desired_state_of_world populator starts
1182 I0615 17:30:24.451093   20555 volume_manager.go:243] Starting Kubelet Volume Manager
1183 I0615 17:30:24.451106   20555 desired_state_of_world_populator.go:131] Desired state populator starts to run
1184 E0615 17:30:24.451547   20555 remote_runtime.go:184] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: des     c = "transport: Error while dialing dial unix /run/virtlet.sock: connect: connection refused"

**What you expected to happen**:
Kubelet should not panic since client did not do anything. Also this is not happening consistently.

**How to reproduce it (as minimally and precisely as possible)**:
arktos-up.sh

**Anything else we need to know?**:
Log forward to Yunwen

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):  ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
```
901 func (m *kubeGenericRuntimeManager) removeContainer(containerID string) error {
902   klog.V(4).Infof("Removing container %q", containerID)
903   // Call internal container post-stop lifecycle hook.
904   if err := m.internalLifecycle.PostStopContainer(containerID); err != nil {
905      return err
906   }
907
908   // Remove the container log.
909   // TODO: Separate log and container lifecycle management.
910   if err := m.removeContainerLog(containerID); err != nil {
911      return err
912   }
913   // Remove the container.
914   runtimeService, _ := m.GetRuntimeServiceByContainerIDString(containerID)
915   return runtimeService.RemoveContainer(containerID)
916 }
```

Can you check error in line 914? If not found, don't RemoveContainer

**Comment by yb01** [comment]
bug understood. will provide a fix shortly since this could be a wider hit. some might temporarily some might be permanent in the cluster depending on when the runtime service will be ready.
 
the root cause for the bug is in the blow function when we query the containerID from runtime one by one. this bug is introduced when we enable the partial runtime readiness feature where one runtime can be in a "unavailable" state when the cluster start "functioning" on the regular container workload type pods.

there is chance when the VM runtime service is queries first and it might not be ready at early stage of the cluster start up time, or it might never get into the ready state when it is ignored. this function will return error.

before the partial runtime readiness feature in Arktos, this should not happen ( or the chance is fairly low --- only during the window when one of the runtime is down and before the agent make the node as not-ready). the callers to this function explicitly skip the error checking here.

```
// TODO: build pod-container relationship map and get the runtime service from the pod-runtimeService map first
func (m *kubeGenericRuntimeManager) GetRuntimeServiceByContainerIDString(id string) (internalapi.RuntimeService, error) {
	klog.V(4).Infof("Retrieve runtime service for containerID %s", id)
	runtimeServices, err := m.runtimeRegistry.GetAllRuntimeServices()
	if err != nil {
		klog.Errorf("GetAllRuntimeServices failed: %v", err)
		return nil, err
	}

	var filter *runtimeapi.ContainerFilter

	for _, runtimeService := range runtimeServices {
		resp, err := runtimeService.ServiceApi.ListContainers(filter)
		if err != nil {
			klog.Errorf("ListPodSandbox failed: %v", err)
			return nil, err
		}

		for _, item := range resp {
			if item.Id == id {
				klog.V(4).Infof("Got runtime service [%v] for containerID %s", runtimeService, id)
				return runtimeService.ServiceApi, nil
			}
		}
	}

	return nil, fmt.Errorf("cannot find specified runtime for ContainerID: %v", id)
}
```
