### ISSUE TITLE
Should a tenant with the same name as the system tenant be allowed to be created?

### ISSUE THREAD

**Issue by ZongbaoLiu** [futurewei-cloud/arktos#374]
There is a default tenant called system, and it cannot be queried.
```
root@arktos:/home/arktos# kubectl get tenant
No resources found.
root@arktos:/home/arktos# kubectl get namespace
NAME              STATUS   AGE     TENANT
default           Active   4m33s   system
kube-node-lease   Active   4m39s   system
kube-public       Active   4m39s   system
kube-system       Active   4m39s   system
```
Then I create a tenant with the same as the system tenant. It succeeded and I can see this tenant. 
```
root@arktos:/home/arktos# kubectl create tenant system
setting storage cluster to system
tenant/system created
root@arktos:/home/arktos# kubectl get tenant
NAME     STORAGEID   STATUS   AGE
system   system      Active   13s
```
But I can only see namespaces of previous tenant.
```
root@arktos:/home/arktos# kubectl get namespace
NAME              STATUS   AGE     TENANT
default           Active   5m26s   system
kube-node-lease   Active   5m32s   system
kube-public       Active   5m32s   system
kube-system       Active   5m32s   system
```
I can't delete this tenant either, because it checked that I was deleting the system tenant.
```
root@arktos:/home/arktos# kubectl delete tenant system
Error from server (Forbidden): tenants "system" is forbidden: this tenant may not be deleted
```
So, I want to know if I should be allowed to create a tenant with the same name as the system tenant.

**Comment by pdgetrf** [comment]
taking a look.

**Comment by pdgetrf** [comment]
we have a tracking issue for this https://github.com/futurewei-cloud/arktos/issues/386

the short answer is "no we don't allow user to create system tenant"

**Comment by XiaoningDing** [comment]
Qian already has a PR in review.  This will be blocked.

**Comment by chenqianfzh** [comment]
The fixing PR https://github.com/futurewei-cloud/arktos/pull/399 is already checked in. Closing the issue.
