### ISSUE TITLE
Pod in a tenant created namespace does not get scheduled

### ISSUE THREAD

**Issue by vinaykul** [futurewei-cloud/arktos#379]
**What happened**: 
1. As tenant-admin create a namespace: kubectl create ns foo
2. Create a pod in that namespace: kubectl -n foo create -f 1pod.yaml
3. Get pod: kubectl get po --all-namespaces -owide
4. Describe pod 1pod to check status.

**What you expected to happen**: 1pod should come up and running.

**How to reproduce it (as minimally and precisely as possible)**:
```
root@ip-172-31-38-225:~/ARK# cat ~/YML/1pod.yml 
apiVersion: v1
kind: Pod
metadata:
  name: 1pod
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 2
  containers:
  - name: stress
    image: skiibum/ubuntu-stress:18.10
    resources:
      limits:
        cpu: "2"
        memory: "2Gi"
        ephemeral-storage: "1Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
        ephemeral-storage: "1Gi"

root@ip-172-31-38-225:~/ARK# kubectl create ns foo
namespace/foo created
root@ip-172-31-38-225:~/ARK# kubectl -n foo create -f ../YML/1pod.yml 
pod/1pod created
root@ip-172-31-38-225:~/ARK#
root@ip-172-31-38-225:~/ARK# kubectl get ns -owide
NAME          STATUS   AGE     TENANT
default       Active   4h18m   vinay-1
foo           Active   4m50s   vinay-1
kube-public   Active   4h18m   vinay-1
kube-system   Active   4h18m   vinay-1
root@ip-172-31-38-225:~/ARK# kubectl get po --all-namespaces -owide
NAMESPACE   NAME   HASHKEY               READY   STATUS    RESTARTS   AGE     IP            NODE               NOMINATED NODE   READINESS GATES
default     1pod   6781352353242108456   1/1     Running   0          72m     10.88.26.75   ip-172-31-27-125   <none>           <none>
foo         1pod   5994107185650809231   0/1     Pending   0          2m54s   <none>        <none>             <none>           <none>
root@ip-172-31-38-225:~/ARK#

```

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`): 
```
root@ip-172-31-38-225:~/ARK# kubectl version
Client Version: version.Info{Major:"0", Minor:"2+", GitVersion:"v0.2-93+6130e0381650c4", GitCommit:"6130e0381650c4bf20bccf5d1e0c64d126c35bda", GitTreeState:"clean", BuildDate:"2020-06-16T20:47:02Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"0", Minor:"2+", GitVersion:"v0.2-84+29b3b2f1921680-dirty", GitCommit:"29b3b2f1921680c2511abe93c8f58d2acba272a2", GitTreeState:"dirty", BuildDate:"2020-06-10T21:45:04Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pdgetrf** [comment]
I am able to create a namespace and then create a pod in it, and it goes into running:

![image](https://user-images.githubusercontent.com/252020/84852712-59c1e280-b012-11ea-9949-3c36a6690ffc.png)

what was the reason of pending in your test?

**Comment by vinaykul** [comment]
It was resource constraint for scheduling. The describe command didn't show scheduling failed due to no suitable node available - out of resource. It was just empty - I was under the impression it should show some error in describe. Anyways. closing this as it works as expected.
