### ISSUE TITLE
kubectl apply/create -f to create namespace will fail if the metadata.tenant is defined, even if the tenant name is correct

### ISSUE THREAD

**Issue by chenqianfzh** [futurewei-cloud/arktos#401]
qianchen@qianchen-VirtualBox:~/bugbash$ kubectl apply -f ~/gopath/qianc/arktos/test/yaml/multi_tenancy_examples/tenant1-ns-a.yaml
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "sample-namespace-a", Namespace: "", Tenant: "qian-5"
Object: &{map["apiVersion":"v1" "kind":"Namespace" "metadata":map["annotations":map["kubectl.kubernetes.io/last-applied-configuration":""] "name":"sample-namespace-a" "tenant":"qian-5"]]}
from server for: "/home/qianchen/gopath/qianc/arktos/test/yaml/multi_tenancy_examples/tenant1-ns-a.yaml": namespaces "sample-namespace-a" is forbidden: User "admin" cannot get resource "namespaces" in API group "" in the namespace "sample-namespace-a"

**Comment by XiaoningDing** [comment]
It works with my client connecting to the test server. Qian will try to repro.

**Comment by chenqianfzh** [comment]
Turned out to be a config issue in my local dev box. Closing it.
