### ISSUE TITLE
Excessive Network-controller update error in perf test

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#471]
**What happened**:
In multiple api server performance test, there are 2210 network controller update error in 33 min (1:24:22 - 1:57:38)
Network_controller.go:176 Network-controller update error (Operation cannot be fulfilled on pods "saturation-deployment-0-5c568bc7fc-4thqb": the object has been modified; please apply your changes to the latest version and try again).

Correspondingly, 2140 out of 2144 PATCH request from network-controller failed:
kube-apiserver.log-20200709-1594259420.gz:I0709 01:22:13.099821       1 wrap.go:47] PATCH /api/v1/nodes/hollow-node-s2bhc: (2.248854ms) 422 [kube-controller-manager/v0.2 (linux/amd64) kubernetes/758291d/system:serviceaccount:kube-system:node-controller 34.94.221.148:46098]

**What you expected to happen**:
Much less failure rate. Seems like missing reread and retry logic.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
arktos 06/29/2020 build
commit 8b7b6554fb46e08f0bad5968a563857d0ad4c55f

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dingyin** [comment]
https://github.com/futurewei-cloud/arktos/pull/477
