### ISSUE TITLE
perf-tests: SchedulingThroughput with apiserver data partition (2 apiserver) is lower than without apiserver data partition

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#485]
**What happened**:
run perf-tests (500 hollow-node) with apiserver data partition (2 apiserver) and without apiserver data partition, then compare schedulingthroughpu. 
with apiserver data partition - 2 apiserver:
```
{
  "average": 11.612903225806452,
  "perc50": 14.4,
  "perc90": 20,
  "perc99": 20.2
}
```
without apiserver - default apiserver:
```
{
  "average": 18.63354037267079,
  "perc50": 19.8,
  "perc90": 20,
  "perc99": 20.2
}
```

**What you expected to happen**:
schedulingthroughput with 2 apiserver shouldn't be lower than 1 apiserver.
**How to reproduce it (as minimally and precisely as possible)**:
1. following instruction to run perf-test: https://github.com/sonyafenge/arktos-tool/blob/master/perftools/Howtorunperf-tests.md
2. check result: SchedulingThroughput_density_*.json
**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):commit 8b7b6554fb46e08f0bad5968a563857d0ad4c55f
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
This issue is resolved.
