### ISSUE TITLE
Kube controlller manager is not able to renew leader token in 500 nodes perf test 

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#534]
**What happened**:
Kube controller manager crashes most of the times in 500 nodes performance test when leader election is enabled.

**What you expected to happen**:
Community version KCM does not crash in same perf test.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sonyafenge** [comment]
duplicate with https://github.com/futurewei-cloud/arktos/issues/538
