### ISSUE TITLE
Task: finish the VM vertical scaling for cpu/memory

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#565]
**What would you like to be added**:

**Why is this needed**:

**Comment by yb01** [comment]
subtask:
https://github.com/futurewei-cloud/arktos-vm-runtime/issues/51
https://github.com/futurewei-cloud/arktos-vm-runtime/issues/52

**Comment by zmn223** [comment]
futurewei-cloud/arktos-vm-runtime#51
futurewei-cloud/arktos-vm-runtime#52
