### ISSUE TITLE
Task: Add unit tests and check UT coverage for multiple controller managers

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#569]
**What would you like to be added**:

**Why is this needed**:

**Comment by Sindica** [comment]
. pkg/cloudfabric-controller/controllerframework:
    - controller_framework.go - 75.3%
    - controller_framework_utils.go - 100%
    - controlerinstancemanager.go - 75.8%

Rest of code are inherited from RS/Deployment controller or controller manager. We have integration test for some of them.

**Comment by Sindica** [comment]
Resolving
