### ISSUE TITLE
Task: verify multiple controller managers will help improve system throughput

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#573]
**What would you like to be added**:
Currently WCM QPS is 20, Scheduler QPS is 50, KCM QPS is 20. We need to verify:
1. Adjust Scheduler QPS to 200. Check 2/3/4/5/6/7/8/9/10 WCM throughput in 500 nodes
2. Adjust Scheduler QPS to 200. Adjust KCM QPS to test limit in 500 nodes

**Why is this needed**:

**Comment by Sindica** [comment]
Used this commit https://github.com/Sindica/arktos/commit/c709bee0a48ad644c194e97e42e32edf06d39262 on https://github.com/Sindica/arktos/commits/rateLimiter to test 3/4/5 workload controller managers with Scheduler QPS updated to 200.

500 nodes Perftest. In 3/4/5 workload controller managers cases, initial throughput was 20*numOfControllers. Once some namespaces were done scheduling, the throughput started to drop. Looks like test data distribution issue. In current perf test, one deployment has only one replicaset, each replicaset is responsible for creating 3000 pods. When most controllers are not working, the throughput drops dramatically.

Current test data generation does not make sense for more than 5 workload controller managers.

Result for 3 WCM:
{
  "perc50": 20,
  "perc90": 60,
  "perc99": 70.8,
  "max": 70.8
}

4 WCM:
{
  "perc50": 38.4,
  "perc90": 80,
  "perc99": 80.2,
  "max": 80.2
}

5 WCM:
{
  "perc50": 20.6,
  "perc90": 80,
  "perc99": 96.8,
  "max": 96.8
}

**Comment by Sindica** [comment]
Resolving
