### ISSUE TITLE
Automatically set up test environments for data partitioned environment

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#62]
**What would you like to be added**:
Currently, multiple api servers with data parition support are in place. We need to make test environment set up easily for the following senario:
1. Single ETCD cluster
2. Two or more api servers with data parition
3. One kube controller manager
4. One scheduler
5. Two workload controller mangers

Ideal output:
Option 1: a script with input arguments to set up one or two api servers
Option 2: incorporate into kubeadm
Option 3: Open for discussion

**Why is this needed**:
Facilitate dev experience and test. Possibly will used in performance test (kube-up)

**Comment by jshaofuturewei** [comment]
I have worked out a script to set up 2  or more apiservers in one aws instance.
For option 1, we might run the script with params to set up 
I am still working on option 2 to see if it is easy to implement or not.

**Comment by jshaofuturewei** [comment]
It is now separated into the following parts
1. Install etcd script 3/10
2. Install updated arktos-up.sh  3/10
3. Install another kube-apiserver and join the cluster set up in 2 3/12
4. Test  and code review 3/12

**Comment by jshaofuturewei** [comment]
Have a discussion with Ying and Xiaoning. Here are the updates. 

1. Arktos-up.sh is used for single server only and there is a another arktos-worker-up.sh for muttile servers. However, the script is used to set up kubernetes only.  
  -- Etcd has to install in new apiserver instances and then added to the existing etcd cluster
 
2. Arktop-up.sh does not generate tokens. As Ying mentioned, it might not be safe to use kubelet tokens to start kube-apiserver. 
  --New certificates will create locally and copied to other servers. 

3. For multiple nodes, please refer to https://github.com/futurewei-cloud/arktos/blob/master/docs/setup-guide/multi-node-dev-cluster.md and make changes.

**Comment by Sindica** [comment]
https://github.com/futurewei-cloud/arktos/pull/116
https://github.com/futurewei-cloud/arktos/pull/118

**Comment by jshaofuturewei** [comment]
https://github.com/futurewei-cloud/arktos/pull/121
https://github.com/futurewei-cloud/arktos/pull/130
