### ISSUE TITLE
Kubelet log: updating kernel flag: kernel/panic, expected value: 10, actual value: -1

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#654]
**What happened**:
found this information in kublet log when run perf-tests, need investigate if this is a real panic:
```
Aug 31 00:32:12 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3382]: I0831 00:32:12.683148    3382 container_manager_linux.go:391] Updating kernel flag: kernel/panic, expected value: 10, actual value: -1
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Logs are located under GCP workload-controller-manager project:
sonya-uswest2: /home/sonyali/logs/perf-test/gce-10000/arktos/0830-build0817-upgrade15000-3api-2wc-1etcd/logs/crashed/kubemarkmaster
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by panda98004** [comment]
Community has a fix and need to create PR to push the fix to Arktos (by today)

**Comment by sonyafenge** [comment]
### 9/11/2020 [perf-tests][arktos][node10000] node10k-3a0w1e
I still got this repro after apply fix PR. Run detail: 10K nodes with 3 apiserver, workload disabled, 1 etcd. 
Error information in kubelet logs:
```
Sep 11 21:26:48 node10k-3a0w1e-kubemark-master kubelet[2794]: I0911 21:26:48.336425    2794 container_manager_linux.go:391] Updating kernel flag: kernel/panic, expected value: 10, actual value: -1
``` 
```
commit 77c19b288b34bd48073f71a735b65212abc9a252
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 7376575673a961373cd8f3be4066ad51f24a6932
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 642ad9ca4621b3905a3b9ee107a1b5c26acdb034
Author: Vinay Kulkarni <vinaykul@users.noreply.github.com>
Date:   Fri Sep 11 13:01:25 2020 -0700

    Fix 'updating kernel flag panic' issue in kubelet during perf tests (#685)
```
logs can be found under GCP project: workload-controller-manager:
sonya-uswest2: /home/sonyali/logs/perf-test/gce-10000/arktos/0911-node10k-3a0w1e

**Comment by jshaofuturewei** [comment]
Ran 5k nodes with 3 api servers 2 workload controller managers  and 1 etcd server and still get the same error

Sep 12 13:39:13 node5000-3api-2wc-1etcd-kubemark-master kubelet[2756]: I0912 13:39:13.464475    2756 container_manager_linux.go:391] Updating kernel flag: kernel/panic, expected value: 10, actual value: -1

commit 642ad9ca4621b3905a3b9ee107a1b5c26acdb034
Author: Vinay Kulkarni <vinaykul@users.noreply.github.com>
Date:   Fri Sep 11 13:01:25 2020 -0700

    Fix 'updating kernel flag panic' issue in kubelet during perf tests (#685)

**Comment by vinaykul** [comment]
Looking at the code closely, this is just a log entry that logs kernel.panic flag being set via sysctl. The sysctl call seems to succeed, so this is a non-issue. The log is present in upstream 1.18.5 as well.

It is issued by the following code in kubelet/cm/container_manager_linux.go
```
                case KernelTunableModify:
                        klog.V(2).Infof("Updating kernel flag: %v, expected value: %v, actual value: %v", flag, expectedValue, val)
                        err = sysctl.SetSysctl(flag, expectedValue)
                        if err != nil {
                                errList = append(errList, err)
                        }
```

The real panic in that log file is the send on closed channel issue.

**Comment by vinaykul** [comment]
Closing - not an issue.
