### ISSUE TITLE
panic: runtime error: index out of range in workload-controller-manager log

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#658]
**What happened**:
```
panic: runtime error: index out of range
 
goroutine 291 [running]:
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Config).updateConfig(0xc000639140)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/config.go:196 +0x73e
k8s.io/kubernetes/vendor/k8s.io/client-go/rest.NewAggregatedConfig.func1(0xc000639140)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/config.go:84 +0xc3
created by k8s.io/kubernetes/vendor/k8s.io/client-go/rest.NewAggregatedConfig
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/config.go:81 +0xdc
using controller configuration from  /etc/srv/kubernetes/workload-controller-manager/controllerconfig.json
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Logs are located under workload-controller-manger project at:  sonya-uswest2: /home/sonyali/logs/perf-test/gce-10000/arktos/0830-upgrade15000-3api-2wc-1etcd/logs/
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
Dup of https://github.com/futurewei-cloud/arktos/issues/639
