### ISSUE TITLE
extract tenant from kubectl config file

### ISSUE THREAD

**Issue by pdgetrf** [futurewei-cloud/arktos#69]
**What would you like to be added**:

kubectl config set-context goose-context-2 --cluster=local-up-cluster --namespace=goose --user=fatgoose --tenant=goosecompany

--tenant flag is not taking effect

**Why is this needed**:

to provide tenant info for rbac validation

**Comment by XiaoningDing** [comment]
It could be "-tenant" or "-space"?

**Comment by XiaoningDing** [comment]
Done.
