### ISSUE TITLE
Verify whether ETCD customization has impact on ETCD performance

### ISSUE THREAD

**Issue by Sindica** [futurewei-cloud/arktos#694]
Step 1: Make sure current Arktos works with ETCD 3.4.4
Step 2: Perf test running on ETCD 3.4.4

**Comment by sonyafenge** [comment]
Started two 5K runs, both disabled workload-controller-manager. Still see killing connection/stream #621, but didn’t see send on closed channel #645.
Both run has a new panic in kube-controller-manager.log: Panic: "invalid memory address or nil pointer dereference" in daemon_controller.go #698
 
Here is run detail:
1. etcd Version: 3.4.4-arktos.1
> Commit 7983fde257f77bdb178197517ae0269711c68f27 on 9/8 with ETCD_SNAPSHOT=20000 and disable workload-controller-manager
> 1 apiserver, 0 workload, 1 etcd
> etcd size after crashed: 2.2GB
> logs can be found under GCP project: workload-controller-manager: sonya-uswest21:  /home/sonyali/logs/perf-test/gce-5000/arktos/0908-debug-1a1w1e
2. etcd Version: 3.4.4:
> Commit “multi-tenancy CRD e2e tests (#662)” on 9/8 with disable workload-controller-manager
> 1 apiserver, 0 workload, 1 etcd
> etcd size after crashed: 1.5GB
> logs can be found under GCP project: workload-controller-manager:  sonya-useast1: /home/sonyali/logs/perf-test/gce-5000/arktos/0908-etcd344-1a1w1e
