### ISSUE TITLE
core-dns pod in customer vpc failing health checks

### ISSUE THREAD

**Issue by clu2xlu** [futurewei-cloud/arktos#742]
**What happened**:
We noticed an issue with customer vpc (vpc1) network: 

In a customer vpc, the core-dns pod failed to start due to failing the health check, see log below: 

As you can see from the log, the expected behavior should be: vpc1 core-dns pod should ping kubernetes-my-net-mizar-vpc1 ip address 12.2.0.2
However, vpc1 core-dns pod is pinging 10.0.0.1, which is default/Kubernetes ‘s ip address. 

**What you expected to happen**:
the expected behavior should be: vpc1 core-dns pod should ping kubernetes-my-net-mizar-vpc1 ip address 12.2.0.2

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a custom vpc (called vpc1) and subnet
2. Create a arktos network that is associated with that customer vpc
3. Check the dns services
4. kubectl get pods -AT
    where it shows core-dns pods
5. kubectl --namespace kube-system logs coredns-my-net-mizar-vpc1
6. you will see health check failure but the ip address is not custom vpc's kubernetes service. Instead, it uses default kubernetes

**Anything else we need to know?**:
the default vpc (vpc0) works as designed. Only customer vpc does not work

**Environment**:
- Arktos version (0.3`):
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): 5.6.0-rc2
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by clu2xlu** [comment]
log: 
ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl get endpoints -AT
TENANT   NAMESPACE     NAME                         ENDPOINTS                               AGE     SERVICEGROUPID
system   default       kubernetes                   172.31.19.222:6443                      21m     1
system   kube-system   kube-dns                     20.0.0.5:53,20.0.0.5:53                 20m
system   kube-system   kube-dns-my-net-mizar-vpc0   20.0.0.2:53,20.0.0.2:53,20.0.0.2:9153   10m
system   kube-system   kube-dns-my-net-mizar-vpc1                                           7m42s
ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl get pods -AT
TENANT   NAMESPACE     NAME                                         HASHKEY               READY   STATUS    RESTARTS   AGE
system   default       mizar-daemon-rmmlg                           7767213986685780088   1/1     Running   0          13m
system   default       mizar-operator-778b867947-t24d6              735919972758241397    1/1     Running   0          13m
system   kube-system   coredns-my-net-mizar-vpc0-7448976c4d-drfmk   980224902440174342    1/1     Running   0          11m
system   kube-system   coredns-my-net-mizar-vpc1-59756cf7d-8dk4m    5050504534201564395   0/1     Running   4          8m6s
system   kube-system   kube-dns-6fdcc959b4-qpptp                    8121308112454169817   3/3     Running   0          21m
system   kube-system   virtlet-j8pvc                                8041115816908773701   3/3     Running   0          21m
ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl --namespace kube-system logs coredns-my-net-mizar-vpc1-59756cf7d-8dk4m
.:53
[INFO] plugin/reload: Running configuration MD5 = 201674b4a1d7573a4b37eaef9d28ac5d
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:39818->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:44515->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:58887->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:35410->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:52075->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:34386->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:60945->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:54103->172.31.0.2:53: i/o timeout
I0918 03:24:53.401140       1 trace.go:116] Trace[911902081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.4005985 +0000 UTC m=+0.020609054) (total time: 30.000511261s):
Trace[911902081]: [30.000511261s] [30.000511261s] END
E0918 03:24:53.401189       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Get "https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:24:53.401141       1 trace.go:116] Trace[1427131847]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.400465918 +0000 UTC m=+0.020476386) (total time: 30.000581313s):
Trace[1427131847]: [30.000581313s] [30.000581313s] END
E0918 03:24:53.401213       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Namespace: Get "https://10.0.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:24:53.401166       1 trace.go:116] Trace[939984059]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.400590309 +0000 UTC m=+0.020600851) (total time: 30.000481493s):
Trace[939984059]: [30.000481493s] [30.000481493s] END
E0918 03:24:53.401233       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Get "https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:53137->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:39998->172.31.0.2:53: i/o timeout
I0918 03:25:24.255846       1 trace.go:116] Trace[208240456]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.255148248 +0000 UTC m=+30.875158889) (total time: 30.000665277s):
Trace[208240456]: [30.000665277s] [30.000665277s] END
E0918 03:25:24.255880       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Namespace: Get "https://10.0.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:25:24.329615       1 trace.go:116] Trace[1106410694]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.329027401 +0000 UTC m=+30.949037935) (total time: 30.000556557s):
Trace[1106410694]: [30.000556557s] [30.000556557s] END
E0918 03:25:24.329641       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Get "https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:25:24.751513       1 trace.go:116] Trace[460128162]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.750906411 +0000 UTC m=+31.370917032) (total time: 30.000574275s):
Trace[460128162]: [30.000574275s] [30.000574275s] END
E0918 03:25:24.751546       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Get "https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl get services -AT
TENANT   NAMESPACE     NAME                           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
system   default       kubernetes                     ClusterIP   10.0.0.1     <none>        443/TCP                  22m
system   default       kubernetes-my-net-mizar-vpc0   ClusterIP   20.0.0.9     <none>        443/TCP                  12m
system   default       kubernetes-my-net-mizar-vpc1   ClusterIP   12.2.0.2     <none>        443/TCP                  9m18s
system   kube-system   kube-dns                       ClusterIP   10.0.0.10    <none>        53/UDP,53/TCP            22m
system   kube-system   kube-dns-my-net-mizar-vpc0     ClusterIP   20.0.0.14    <none>        53/UDP,53/TCP,9153/TCP   12m
system   kube-system   kube-dns-my-net-mizar-vpc1     ClusterIP   12.2.0.5     <none>        53/UDP,53/TCP,9153/TCP   9m18s

**Comment by clu2xlu** [comment]
`ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl get endpoints -AT
TENANT   NAMESPACE     NAME                         ENDPOINTS                               AGE     SERVICEGROUPID
system   default       kubernetes                   172.31.19.222:6443                      21m     1
system   kube-system   kube-dns                     20.0.0.5:53,20.0.0.5:53                 20m
system   kube-system   kube-dns-my-net-mizar-vpc0   20.0.0.2:53,20.0.0.2:53,20.0.0.2:9153   10m
system   kube-system   kube-dns-my-net-mizar-vpc1                                           7m42s
ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl get pods -AT
TENANT   NAMESPACE     NAME                                         HASHKEY               READY   STATUS    RESTARTS   AGE
system   default       mizar-daemon-rmmlg                           7767213986685780088   1/1     Running   0          13m
system   default       mizar-operator-778b867947-t24d6              735919972758241397    1/1     Running   0          13m
system   kube-system   coredns-my-net-mizar-vpc0-7448976c4d-drfmk   980224902440174342    1/1     Running   0          11m
system   kube-system   coredns-my-net-mizar-vpc1-59756cf7d-8dk4m    5050504534201564395   0/1     Running   4          8m6s
system   kube-system   kube-dns-6fdcc959b4-qpptp                    8121308112454169817   3/3     Running   0          21m
system   kube-system   virtlet-j8pvc                                8041115816908773701   3/3     Running   0          21m
ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl --namespace kube-system logs coredns-my-net-mizar-vpc1-59756cf7d-8dk4m
.:53
[INFO] plugin/reload: Running configuration MD5 = 201674b4a1d7573a4b37eaef9d28ac5d
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:39818->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:44515->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:58887->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:35410->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:52075->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:34386->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:60945->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:54103->172.31.0.2:53: i/o timeout
I0918 03:24:53.401140       1 trace.go:116] Trace[911902081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.4005985 +0000 UTC m=+0.020609054) (total time: 30.000511261s):
Trace[911902081]: [30.000511261s] [30.000511261s] END
E0918 03:24:53.401189       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Get "https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:24:53.401141       1 trace.go:116] Trace[1427131847]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.400465918 +0000 UTC m=+0.020476386) (total time: 30.000581313s):
Trace[1427131847]: [30.000581313s] [30.000581313s] END
E0918 03:24:53.401213       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Namespace: Get "https://10.0.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:24:53.401166       1 trace.go:116] Trace[939984059]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.400590309 +0000 UTC m=+0.020600851) (total time: 30.000481493s):
Trace[939984059]: [30.000481493s] [30.000481493s] END
E0918 03:24:53.401233       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Get "https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:53137->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:39998->172.31.0.2:53: i/o timeout
I0918 03:25:24.255846       1 trace.go:116] Trace[208240456]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.255148248 +0000 UTC m=+30.875158889) (total time: 30.000665277s):
Trace[208240456]: [30.000665277s] [30.000665277s] END
E0918 03:25:24.255880       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Namespace: Get "https://10.0.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:25:24.329615       1 trace.go:116] Trace[1106410694]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.329027401 +0000 UTC m=+30.949037935) (total time: 30.000556557s):
Trace[1106410694]: [30.000556557s] [30.000556557s] END
E0918 03:25:24.329641       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Get "https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:25:24.751513       1 trace.go:116] Trace[460128162]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.750906411 +0000 UTC m=+31.370917032) (total time: 30.000574275s):
Trace[460128162]: [30.000574275s] [30.000574275s] END
E0918 03:25:24.751546       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Get "https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
ubuntu@ip-172-31-19-222:~/go/src/k8s.io/mizar/mizar/obj/tests$ kubectl get services -AT
TENANT   NAMESPACE     NAME                           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
system   default       kubernetes                     ClusterIP   10.0.0.1     <none>        443/TCP                  22m
system   default       kubernetes-my-net-mizar-vpc0   ClusterIP   20.0.0.9     <none>        443/TCP                  12m
system   default       kubernetes-my-net-mizar-vpc1   ClusterIP   12.2.0.2     <none>        443/TCP                  9m18s
system   kube-system   kube-dns                       ClusterIP   10.0.0.10    <none>        53/UDP,53/TCP            22m
system   kube-system   kube-dns-my-net-mizar-vpc0     ClusterIP   20.0.0.14    <none>        53/UDP,53/TCP,9153/TCP   12m
system   kube-system   kube-dns-my-net-mizar-vpc1     ClusterIP   12.2.0.5     <none>        53/UDP,53/TCP,9153/TCP   9m18s`

**Comment by clu2xlu** [comment]
`kubectl get pods -AT
TENANT   NAMESPACE     NAME                                         HASHKEY               READY   STATUS    RESTARTS   AGE
system   default       mizar-daemon-rmmlg                           7767213986685780088   1/1     Running   0          13m
system   default       mizar-operator-778b867947-t24d6              735919972758241397    1/1     Running   0          13m
system   kube-system   coredns-my-net-mizar-vpc0-7448976c4d-drfmk   980224902440174342    1/1     Running   0          11m
system   kube-system   coredns-my-net-mizar-vpc1-59756cf7d-8dk4m    5050504534201564395   0/1     Running   4          8m6s
system   kube-system   kube-dns-6fdcc959b4-qpptp                    8121308112454169817   3/3     Running   0          21m
system   kube-system   virtlet-j8pvc                                8041115816908773701   3/3     Running   0          21m`

**Comment by clu2xlu** [comment]
```
kubectl get pods -AT
TENANT   NAMESPACE     NAME                                         HASHKEY               READY   STATUS    RESTARTS   AGE
system   default       mizar-daemon-rmmlg                           7767213986685780088   1/1     Running   0          13m
system   default       mizar-operator-778b867947-t24d6              735919972758241397    1/1     Running   0          13m
system   kube-system   coredns-my-net-mizar-vpc0-7448976c4d-drfmk   980224902440174342    1/1     Running   0          11m
system   kube-system   coredns-my-net-mizar-vpc1-59756cf7d-8dk4m    5050504534201564395   0/1     Running   4          8m6s
system   kube-system   kube-dns-6fdcc959b4-qpptp                    8121308112454169817   3/3     Running   0          21m
system   kube-system   virtlet-j8pvc                                8041115816908773701   3/3     Running   0          21m
```

**Comment by clu2xlu** [comment]
```
$ kubectl --namespace kube-system logs coredns-my-net-mizar-vpc1-59756cf7d-8dk4m
.:53
[INFO] plugin/reload: Running configuration MD5 = 201674b4a1d7573a4b37eaef9d28ac5d
CoreDNS-1.7.0
linux/amd64, go1.14.4, f59c03d
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:39818->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:44515->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:58887->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:35410->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:52075->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:34386->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:60945->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:54103->172.31.0.2:53: i/o timeout
I0918 03:24:53.401140       1 trace.go:116] Trace[911902081]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.4005985 +0000 UTC m=+0.020609054) (total time: 30.000511261s):
Trace[911902081]: [30.000511261s] [30.000511261s] END
E0918 03:24:53.401189       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Get "https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:24:53.401141       1 trace.go:116] Trace[1427131847]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.400465918 +0000 UTC m=+0.020476386) (total time: 30.000581313s):
Trace[1427131847]: [30.000581313s] [30.000581313s] END
E0918 03:24:53.401213       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Namespace: Get "https://10.0.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:24:53.401166       1 trace.go:116] Trace[939984059]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:23.400590309 +0000 UTC m=+0.020600851) (total time: 30.000481493s):
Trace[939984059]: [30.000481493s] [30.000481493s] END
E0918 03:24:53.401233       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Get "https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:53137->172.31.0.2:53: i/o timeout
[ERROR] plugin/errors: 2 2774764950619035068.7970601179162709452. HINFO: read udp 12.2.0.6:39998->172.31.0.2:53: i/o timeout
I0918 03:25:24.255846       1 trace.go:116] Trace[208240456]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.255148248 +0000 UTC m=+30.875158889) (total time: 30.000665277s):
Trace[208240456]: [30.000665277s] [30.000665277s] END
E0918 03:25:24.255880       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Namespace: Get "https://10.0.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:25:24.329615       1 trace.go:116] Trace[1106410694]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.329027401 +0000 UTC m=+30.949037935) (total time: 30.000556557s):
Trace[1106410694]: [30.000556557s] [30.000556557s] END
E0918 03:25:24.329641       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Endpoints: Get "https://10.0.0.1:443/api/v1/endpoints?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
I0918 03:25:24.751513       1 trace.go:116] Trace[460128162]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125 (started: 2020-09-18 03:24:54.750906411 +0000 UTC m=+31.370917032) (total time: 30.000574275s):
Trace[460128162]: [30.000574275s] [30.000574275s] END
E0918 03:25:24.751546       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.3/tools/cache/reflector.go:125: Failed to list *v1.Service: Get "https://10.0.0.1:443/api/v1/services?limit=500&resourceVersion=0": dial tcp 10.0.0.1:443: i/o timeout
```

**Comment by clu2xlu** [comment]
```
$ kubectl get services -AT
TENANT   NAMESPACE     NAME                           TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
system   default       kubernetes                     ClusterIP   10.0.0.1     <none>        443/TCP                  22m
system   default       kubernetes-my-net-mizar-vpc0   ClusterIP   20.0.0.9     <none>        443/TCP                  12m
system   default       kubernetes-my-net-mizar-vpc1   ClusterIP   12.2.0.2     <none>        443/TCP                  9m18s
system   kube-system   kube-dns                       ClusterIP   10.0.0.10    <none>        53/UDP,53/TCP            22m
system   kube-system   kube-dns-my-net-mizar-vpc0     ClusterIP   20.0.0.14    <none>        53/UDP,53/TCP,9153/TCP   12m
system   kube-system   kube-dns-my-net-mizar-vpc1     ClusterIP   12.2.0.5     <none>        53/UDP,53/TCP,9153/TCP   9m18s
```

**Comment by h-w-chen** [comment]
talked to Cathy offline; this fix is verified working. closed.
