### ISSUE TITLE
[Node Agent] Virtlet VM is created with wrong QoS class

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#91]
What happened: Create a Guaranteed QoS Virtlet VM by specifying the below YAML.

What you expected to happen: QoS class of the VM should show as guaranteed. It shows up as best effort instead.

How to reproduce it (as minimally and precisely as possible):
See setup instructions in issue #115

Anything else we need to know?:

Environment:

Kubernetes version (use kubectl version):
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release):
Kernel (e.g. uname -a):
Install tools:
Network plugin and version (if this is a network-related bug):
Others:

(This issue is ported from the old repo with original author vinaykul.)

**Comment by yb01** [comment]
Assigned to me. fixed in PR https://github.com/futurewei-cloud/arktos/pull/139 along with fixing the cpu count bug in runtime.
