### ISSUE TITLE
Support persistent block storage volumes for VMs

### ISSUE THREAD

**Issue by XiaoningDing** [futurewei-cloud/arktos#93]
**What would you like to be added**:
Verify at least one remote block storage (preferably Cinder as we need to integrate with OpenStack) works for Arktos. So that VMs still have the same volume when it's restarted, either on same node or a different node.

**Why is this needed**:
VMs need persistent block storage to act as disks.

**Comment by yb01** [comment]
PR https://github.com/futurewei-cloud/arktos/pull/55 along with runtime PR https://github.com/futurewei-cloud/arktos-vm-runtime/pull/16 and https://github.com/futurewei-cloud/arktos-vm-runtime/pull/17 has the fix.
