### ISSUE TITLE
Performance testing: SchedulingThroughput is one fourth of pre-Alkaid

### ISSUE THREAD

**Issue by sonyafenge** [futurewei-cloud/arktos#96]
**What happened**:
performance testing result for SchedulingThroughput_density
Alkaid (01/16 build and 01/20 build):
```
  "average": 4.980833333333334,
  "perc50": 5,
  "perc90": 5,
  "perc99": 5.2
```
Pre-Alkaid (06/18/2019 build)
```
  "average": 19.736842105263147,
  "perc50": 20,
  "perc90": 20,
  "perc99": 20.2
```
**What you expected to happen**:
equal or higher throughput data than base version: commit 75e947641eb1710c25213c1e7c66038833bb5b5b
**How to reproduce it (as minimally and precisely as possible)**:
1. prepare kubemark test environments
2. run kubernetes performance testing:
```
./run-e2e.sh --provider=kubemark --report-dir=[HOME]/logs/perf-test/gce-100/0116 --kubeconfig=[HOME]/go/src/k8s.io/alkaid/test/kubemark/resources/kubeconfig.kubemark --testconfig=testing/density/config.yaml --testconfig=testing/load/config.yaml
```
**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
```
alkaid 01/16 build and 01/20 build
```
- Cloud provider or hardware configuration:
```
Admin master: 1 | e2-standard-8 (8 vCPUs, 32 GB memory)      | cos-73-11647-163-0
Admin nodes: 3 | n1-standard-4 (4 vCPUs, 15 GB memory) |     cos-73-11647-163-0
             5 | n1-standard-8 (8 vCPUs, 30 GB memory) | cos-73-11647-163-0
kubemark master: 1 | e2-standard-8 (8 vCPUs, 32 GB memory)      | cos-beta-73-11647-64-0

Software Build: Pre-Alkaid 06/2019 75e94764, Alkaid 01/16/2020, Alkaid 01/20/2020
Cloud Provider: GCE
```
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sonyafenge** [comment]
Comments from Vinatkul:
Given the latest perf data from Sonya, this is not likely a scheduler issue.
```
Just got the result for 500 nodes, which is 1/21 alkaid build and disabled workload-controller-manager, get the Schedulingthrouput data as below
sonyafenge@sonyadev1:~$ kubectl get co --kubeconfig ~/go/src/k8s.io/alkaid/test/kubemark/resources/kubeconfig.kubemark 
No resources found.
 
sonyafenge@sonyadev1:~$ cat ~/logs/perf-test/gce-500/alkaid/0124/SchedulingThroughput_density_2020-01-24T22:08:15Z.json
{
  "average": 19.86754966887416,
  "perc50": 20,
  "perc90": 20,
  "perc99": 20.2
}
 
It is same as pre-Alkaid.
 
@Ying Huang, You may need take a look from workload controller manager side.
 
Thanks,
Sonya
From: Ying Huang <ying.huang@futurewei.com>
Date: Thursday, January 23, 2020 at 1:28 PM
To: Sonya Li <fenge.li@futurewei.com>, XiaoNing Ding <xiaoning.ding@futurewei.com>, Ying Xiong <ying.xiong@futurewei.com>, Vinay Kulkarni <vinay.kulkarni@futurewei.com>, Joe Shao <joe.shao@futurewei.com>
Subject: Re: Performance testing report draft
 
Hi Vinay,
 
We have checked the number of workers in PreAlkaid should not be an issue. Please take a look at this issue.
 
Thank you,
Ying Huang
From: Sonya Li <fenge.li@futurewei.com>
Sent: Wednesday, January 22, 2020 2:31 PM
To: XiaoNing Ding <xiaoning.ding@futurewei.com>; Ying Xiong <ying.xiong@futurewei.com>; Vinay Kulkarni <vinay.kulkarni@futurewei.com>; Ying Huang <ying.huang@futurewei.com>; Joe Shao <joe.shao@futurewei.com>
Subject: Re: Performance testing report draft
 
+ Vinay.
 
Add 500 nodes with 2 workload-controller-manager to report.
https://efutureway.sharepoint.com/:p:/r/sites/CloudFabric-All/_layouts/15/Doc.aspx?sourcedoc=%7BFC9A59AC-E5E6-4E1D-A0E1-4F4E3461224F%7D&file=Performance%20Testing%20Results.pptx&action=edit&mobileredirect=true
 thanks,
Sonya
From: XiaoNing Ding <xiaoning.ding@futurewei.com>
Date: Tuesday, January 21, 2020 at 10:06 AM
To: Sonya Li <fenge.li@futurewei.com>, Ying Xiong <ying.xiong@futurewei.com>, Jeff Zhu <jeff.zhu@futurewei.com>
Cc: Michael Xie <michael.xie@futurewei.com>, Ying Huang <ying.huang@futurewei.com>, Joe Shao <joe.shao@futurewei.com>
Subject: Re: Performance testing report draft
 
Thanks. Will triage and assign owner.
From: Sonya Li <fenge.li@futurewei.com>
Date: Tuesday, January 21, 2020 at 9:45 AM
To: XiaoNing Ding <xiaoning.ding@futurewei.com>, Ying Xiong <ying.xiong@futurewei.com>, Jeff Zhu <jeff.zhu@futurewei.com>
Cc: Michael Xie <michael.xie@futurewei.com>, Ying Huang <ying.huang@futurewei.com>, Joe Shao <joe.shao@futurewei.com>
Subject: Re: Performance testing report draft
 
I run another performance testing on GCE 500 nodes with yesterday’s Alkaid build, still get the same results.
 
Issue has been opened: https://github.com/futurewei-cloud/alkaid/issues/394
 
Thanks,
Sonya
From: XiaoNing Ding <xiaoning.ding@futurewei.com>
Date: Monday, January 20, 2020 at 4:07 PM
To: Sonya Li <fenge.li@futurewei.com>, Ying Xiong <ying.xiong@futurewei.com>, Jeff Zhu <jeff.zhu@futurewei.com>
Cc: Michael Xie <michael.xie@futurewei.com>, Ying Huang <ying.huang@futurewei.com>, Joe Shao <joe.shao@futurewei.com>
Subject: Re: Performance testing report draft
 
If the same difference can be reproduced, please create an issue to track this scheduling performance degradation.  We will investigate what's going on.
 
thanks,
Xiaoning
From: Sonya Li <fenge.li@futurewei.com>
Sent: Monday, January 20, 2020 3:27 PM
To: Ying Xiong <ying.xiong@futurewei.com>; Jeff Zhu <jeff.zhu@futurewei.com>; XiaoNing Ding <xiaoning.ding@futurewei.com>
Cc: Michael Xie <michael.xie@futurewei.com>; Ying Huang <ying.huang@futurewei.com>; Joe Shao <joe.shao@futurewei.com>
Subject: Re: Performance testing report draft
 
I will try to add multi workload-controller to see any difference after 5000 nodes testing done.
 
Thanks,
Sonya
From: Ying Xiong <ying.xiong@futurewei.com>
Date: Monday, January 20, 2020 at 2:04 PM
To: Sonya Li <fenge.li@futurewei.com>, Jeff Zhu <jeff.zhu@futurewei.com>, XiaoNing Ding <xiaoning.ding@futurewei.com>
Cc: Michael Xie <michael.xie@futurewei.com>, Ying Huang <ying.huang@futurewei.com>, Joe Shao <joe.shao@futurewei.com>
Subject: RE: Performance testing report draft
 
Thanks Sonya.    The Pod start up latency and API responsiveness are virtually no different, which is good, and Alkaid (without scalability part) is as good as K8S.
 
But for scheduling throughput, it is only one fourth of pre-Alkaid. But I don’t think we change scheduler recently.
 
    cid:image001.jpg@01D5CF9A.83176780
 
Thanks
Ying Xiong
Cloud Lab @ Seattle Research Center
Futurewei Technologies, Inc.
From: Sonya Li <fenge.li@futurewei.com> 
Sent: Monday, January 20, 2020 1:39 PM
To: Ying Xiong <ying.xiong@futurewei.com>; Jeff Zhu <jeff.zhu@futurewei.com>; XiaoNing Ding <xiaoning.ding@futurewei.com>
Cc: Michael Xie <michael.xie@futurewei.com>; Ying Huang <ying.huang@futurewei.com>; Joe Shao <joe.shao@futurewei.com>
Subject: Performance testing report draft
 
I have the draft for performance testing report ready. Please kindly review and let me know if you have any suggestions.
 
This report only included GCS 500 nodes density results for Alkaid and pre-Alkaid. I will add more information once we have more data ready.
 
From the current data, Alkaid has pretty good data.
 
https://efutureway.sharepoint.com/:p:/s/CloudFabric-All/EaxZmvzm5R1OoOFPTjRhIk8BbystpRbSQmAtizS1mPBNLg?e=8MbaXz
 
thanks,
Sonya
```

**Comment by jshaofuturewei** [comment]
Talked with Qian and found the following indexers missing hashkey 
MetaNamespaceIndex
indexByPodNodeName 
objInfoKeyFunc

**Comment by jshaofuturewei** [comment]
Add a separate cache and got a little improvement
{
  "average": 7.5,
  "perc50": 5,
  "perc90": 17.2,
  " perc99": 21.2
}

**Comment by sonyafenge** [comment]
https://github.com/futurewei-cloud/arktos/pull/299

**Comment by sonyafenge** [comment]
tested using https://github.com/futurewei-cloud/arktos/pull/299, and still get the same result.
Here is environement detail: 
```
export MASTER_DISK_SIZE=300GB MASTER_ROOT_DISK_SIZE=100GB KUBE_GCE_ZONE=us-west2-b MASTER_SIZE=n1-highmem-32 NODE_SIZE=n1-highmem-8 NUM_NODES=8 NODE_DISK_SIZE=200GB KUBE_GCE_NETWORK=workload-500-nopro GOPATH=$HOME/go KUBE_GCE_ENABLE_IP_ALIASES=true KUBE_GCE_PRIVATE_CLUSTER=true CREATE_CUSTOM_NETWORK=true KUBE_GCE_INSTANCE_PREFIX=workload-500-nopro APISERVERS_EXTRA_NUM=0
```
SchedulingThroughput result:
```
{
  "average": 4.9675,
  "perc50": 5,
  "perc90": 5,
  "perc99": 5
}
```

**Comment by jshaofuturewei** [comment]
I logged into the master server and found all the resources are keeping starting watch within seconds.

I0715 21:56:01.079127       1 get.go:265] Starting watch for /api/v1/endpoints, rv=187944 labels=!service.kubernetes.io/service-proxy-name fields= timeout=9m14s
I0715 21:56:08.656957       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188043 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m44s
I0715 21:56:19.580789       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188169 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m55s
I0715 21:56:19.892127       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188169 labels=!service.kubernetes.io/service-proxy-name fields= timeout=6m17s
I0715 21:56:23.566677       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188250 labels=!service.kubernetes.io/service-proxy-name fields= timeout=5m46s
I0715 21:56:25.277873       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188315 labels=!service.kubernetes.io/service-proxy-name fields= timeout=9m57s
I0715 21:56:28.812869       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188353 labels=!service.kubernetes.io/service-proxy-name fields= timeout=8m15s
I0715 21:56:34.067015       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188408 labels=!service.kubernetes.io/service-proxy-name fields= timeout=6m8s
I0715 21:56:35.054803       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188452 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m29s
I0715 21:56:35.586645       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188452 labels=!service.kubernetes.io/service-proxy-name fields= timeout=9m13s
I0715 21:56:40.318995       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188486 labels=!service.kubernetes.io/service-proxy-name fields= timeout=5m20s
I0715 21:56:41.018456       1 get.go:265] Starting watch for /api/v1/endpoints, rv=188486 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m1s

**Comment by Sindica** [comment]
> I logged into the master server and found all the resources are keeping starting watch within seconds.
> 
> I0715 21:56:01.079127 1 get.go:265] Starting watch for /api/v1/endpoints, rv=187944 labels=!service.kubernetes.io/service-proxy-name fields= timeout=9m14s
> I0715 21:56:08.656957 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188043 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m44s
> I0715 21:56:19.580789 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188169 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m55s
> I0715 21:56:19.892127 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188169 labels=!service.kubernetes.io/service-proxy-name fields= timeout=6m17s
> I0715 21:56:23.566677 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188250 labels=!service.kubernetes.io/service-proxy-name fields= timeout=5m46s
> I0715 21:56:25.277873 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188315 labels=!service.kubernetes.io/service-proxy-name fields= timeout=9m57s
> I0715 21:56:28.812869 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188353 labels=!service.kubernetes.io/service-proxy-name fields= timeout=8m15s
> I0715 21:56:34.067015 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188408 labels=!service.kubernetes.io/service-proxy-name fields= timeout=6m8s
> I0715 21:56:35.054803 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188452 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m29s
> I0715 21:56:35.586645 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188452 labels=!service.kubernetes.io/service-proxy-name fields= timeout=9m13s
> I0715 21:56:40.318995 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188486 labels=!service.kubernetes.io/service-proxy-name fields= timeout=5m20s
> I0715 21:56:41.018456 1 get.go:265] Starting watch for /api/v1/endpoints, rv=188486 labels=!service.kubernetes.io/service-proxy-name fields= timeout=7m1s

The endpoints watch are from hollow node. Each of them has one watch.

**Comment by jshaofuturewei** [comment]
I went through all the resources. Actions, services, nodes, pods, namespaces, and etc have this issues. Those types look like hollow node related. Secrets and pvc looks fine.

**Comment by Sindica** [comment]
> I went through all the resources. Actions, services, nodes, pods, namespaces, and etc have this issues. Those types look like hollow node related. Secrets and pvc looks fine.

Current timeout for watch is 5-10 min (see https://github.com/futurewei-cloud/arktos/issues/486). If single hollow node does not watch same resouce again within 5 min, it is not an issue.

However, we might need to check whether endpoint watch can have more restriction so that it can have less data to be transferred (it is added for multiple api server partitioning).

**Comment by Sindica** [comment]
This issue shall be fixed by change https://github.com/futurewei-cloud/arktos/pull/528

**Comment by Sindica** [comment]
Issue resolved
